name: Npm

on:
  workflow_call:

permissions:
  contents: read

jobs:
  Install:
    name: Install Dependencies and Generate SBOM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          sparse-checkout: |
            .node-version
            package-lock.json
            package.json
          sparse-checkout-cone-mode: false

      - uses: actions/setup-node@v5
        with:
          node-version-file: .node-version
          registry-url: https://registry.npmjs.org
          package-manager-cache: false

      - uses: actions/cache@v4
        id: cache-node_modules
        with:
          path: node_modules
          key: node-modules-ubuntu-latest-${{ hashFiles('package-lock.json') }}

      - if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      - name: Install CycloneDX SBOM generator
        run: npm install --save-dev cyclonedx-node-npm

      - name: Generate CycloneDX SBOM (JSON)
        run: npx cyclonedx-node-npm --output sbom.json --json

      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v3
        with:
          name: SBOM-JSON
          path: sbom.json
